class_name CharacterCatalog
extends RefCounted

const MIN_SLOT_COUNT := 5
const GAME_SCENE_PATH := "res://scenes/Main.tscn"


static func get_characters() -> Array:
	return [
		{
			"id": "mage",
			"name": "마법사",
			"subtitle": "별빛을 다루는 강력한 마법사",
			"concept_title": "컨셉",
			"concept": "별의 힘을 빌려 전장을 지배하는 마법사.\n아름다운 별빛은 적에게는 재앙이 된다.",
			"card_image": "res://assets/players/mage/portraits/player_mage_ultimate_cutin_candidate.png",
			"card_mode": "cover",
			"card_focus": Vector2(0.48, 0.5),
			"sprite_sheet": "res://assets/players/mage/sprites/player_mage_sprite_sheet.png",
			"sprite_scale": Vector2(0.42, 0.42),
			"sprite_position": Vector2(0.0, -8.0),
			"sprite_columns": 8,
			"sprite_rows": 8,
			"combat_script": "res://scripts/combat/mage_combat.gd",
			"ultimate_cutin_image": "res://assets/players/mage/portraits/player_mage_ultimate_character.png",
			"ultimate_cutin_side": "right",
			"ultimate_cutin_width_scale": 0.68,
			"ultimate_cutin_x_offset": 120.0,
			"ultimate_prime_sfx": "res://assets/audio/mage/mage_ultimate_prime.mp3",
			"ultimate_impact_sfx": "res://assets/audio/mage/mage_ultimate_impact.mp3",
			"ultimate_prime_vfx_sheet": "res://assets/players/mage/skills/ultimate/mage_ultimate_prime_sheet.png",
			"ultimate_impact_vfx_sheet": "res://assets/players/mage/skills/ultimate/mage_ultimate_impact_sheet.png",
			"select_background_image": "res://assets/ui/character_select/background_mage_v2.png",
			"select_background_mode": "cover",
			"select_background_focus": Vector2(0.5, 0.5),
			"info_side": "left",
			"info_width": 470.0,
			"detail_image": "res://assets/players/mage/portraits/player_mage_ultimate_cutin_candidate.png",
			"detail_mode": "contain",
			"detail_focus": Vector2(0.5, 0.5),
			"detail_info_side": "left",
			"detail_overlay_color": Color(0.0, 0.0, 0.0, 0.02),
			"theme_color": Color(0.48, 0.68, 1.0),
			"accent_color": Color(1.0, 0.78, 0.34),
			"skills": [
				{
					"name": "에너지 구체",
					"description": "마법 에너지를 구체로 발사하여 적에게 피해를 입힙니다.",
					"icon_label": "✦",
					"icon_shape": "star",
					"icon_path": "",
					"color": Color(0.22, 0.62, 1.0),
				},
				{
					"name": "별빛 광선",
					"description": "하늘에서 별빛 광선을 소환하여 적들을 심판합니다.",
					"icon_label": "✧",
					"icon_shape": "ray",
					"icon_path": "",
					"color": Color(0.65, 0.88, 1.0),
				},
				{
					"name": "마나 베리어",
					"description": "마나의 힘으로 보호막을 생성하여 피해를 흡수합니다.",
					"icon_label": "◌",
					"icon_shape": "barrier",
					"icon_path": "",
					"color": Color(0.35, 0.85, 1.0),
				},
			],
		},
		{
			"id": "hunter",
			"name": "헌터",
			"subtitle": "도심의 그림자를 가르는 집행자",
			"concept_title": "컨셉",
			"concept": "어반 판타지의 밤을 사냥터로 삼는 여자 헌터.\n검은 기계식 에너지소드로 표적을 조용히 집행한다.",
			"card_image": "res://assets/players/hunter/portraits/hunter_select_reference.png",
			"card_mode": "cover",
			"card_focus": Vector2(0.25, 0.48),
			"sprite_sheet": "res://assets/players/hunter/sprites/player_hunter.png",
			"sprite_scale": Vector2(0.42, 0.42),
			"sprite_position": Vector2(0.0, -8.0),
			"sprite_columns": 8,
			"sprite_rows": 8,
			"idle_sheet": "res://assets/players/hunter/sprites/v5/hunter_idle_v5.png",
			"idle_columns": 4,
			"idle_rows": 8,
			"idle_fps": 4.0,
			"walk_sheet": "res://assets/players/hunter/sprites/v5/hunter_walk_v5.png",
			"walk_columns": 8,
			"walk_rows": 8,
			"walk_fps": 10.0,
			"combat_script": "res://scripts/combat/hunter_combat.gd",
			"ultimate_cutin_image": "res://assets/players/hunter/portraits/player_hunter_ultimate_character.png",
			"ultimate_cutin_side": "right",
			"ultimate_cutin_width_scale": 0.58,
			"ultimate_cutin_x_offset": 180.0,
			"ultimate_prime_sfx": "res://assets/audio/hunter/hunter_ultimate_prime.mp3",
			"ultimate_impact_sfx": "res://assets/audio/hunter/hunter_ultimate_impact.mp3",
			"ultimate_prime_vfx_sheet": "res://assets/players/hunter/skills/ultimate/hunter_ultimate_blade_ignite_sheet.png",
			"ultimate_prime_vfx_rotate": true,
			"ultimate_prime_vfx_forward_offset": 54.0,
			"ultimate_impact_vfx_sheet": "res://assets/players/hunter/skills/ultimate/hunter_ultimate_activation_impact_sheet.png",
			"select_background_image": "res://assets/ui/character_select/background_hunter_v2.png",
			"select_background_mode": "cover",
			"select_background_focus": Vector2(0.5, 0.5),
			"info_side": "left",
			"info_width": 470.0,
			"detail_image": "res://assets/players/hunter/portraits/hunter_select_reference.png",
			"detail_mode": "contain",
			"detail_focus": Vector2(0.5, 0.5),
			"detail_info_side": "right",
			"detail_overlay_color": Color(0.0, 0.0, 0.0, 0.04),
			"theme_color": Color(1.0, 0.18, 0.18),
			"accent_color": Color(0.98, 0.58, 0.48),
			"skills": [
				{
					"name": "섀도 스텝",
					"description": "짧은 거리를 빠르게 돌파해 위험한 위치를 벗어납니다.",
					"icon_label": "◇",
					"icon_shape": "step",
					"icon_path": "res://assets/ui/hud/hunter_skill_dash_casual_v2.png",
					"color": Color(0.65, 0.08, 0.1),
				},
				{
					"name": "카운터 엣지",
					"description": "적의 공격 타이밍에 맞춰 검으로 받아치고 빈틈을 만듭니다.",
					"icon_label": "◆",
					"icon_shape": "guard",
					"icon_path": "res://assets/ui/hud/hunter_skill_parry_casual_v2.png",
					"color": Color(1.0, 0.38, 0.22),
				},
				{
					"name": "레드 아크",
					"description": "붉은 에너지 검기를 날려 전방의 적을 베어냅니다.",
					"icon_label": "▣",
					"icon_shape": "slash",
					"icon_path": "res://assets/ui/hud/hunter_skill_sword_wave_casual_v2.png",
					"color": Color(1.0, 0.28, 0.18),
				},
				{
					"name": "블레이드 오버로드",
					"description": "궁극기 게이지를 소모해 에너지소드를 과충전하고 처형 모드에 돌입합니다.",
					"icon_label": "✦",
					"icon_shape": "protocol",
					"icon_path": "res://assets/ui/hud/hunter_skill_ultimate_overload_casual_v1.png",
					"color": Color(1.0, 0.42, 0.18),
				},
			],
		},
		{
			"id": "hunter_experiment",
			"name": "Hunter TEST",
			"subtitle": "Experimental hunter animation test slot",
			"concept_title": "Experiment",
			"concept": "A temporary hunter clone for checking generated attack animation sheets in-game.",
			"card_image": "res://assets/players/hunter/portraits/hunter_select_reference.png",
			"card_mode": "cover",
			"card_focus": Vector2(0.25, 0.48),
			"sprite_sheet": "res://assets/players/hunter/sprites/player_hunter.png",
			"sprite_scale": Vector2(0.42, 0.42),
			"sprite_position": Vector2(0.0, -8.0),
			"sprite_columns": 8,
			"sprite_rows": 8,
			"idle_sheet": "res://assets/players/hunter/sprites/v5/hunter_idle_v5.png",
			"idle_columns": 4,
			"idle_rows": 8,
			"idle_fps": 4.0,
			"walk_sheet": "res://assets/players/hunter/sprites/experiment/hunter_walk_experiment.png",
			"walk_columns": 8,
			"walk_rows": 8,
			"walk_fps": 10.0,
			"attack_sheet": "res://assets/players/hunter/sprites/experiment/hunter_attack_experiment.png",
			"attack_columns": 6,
			"attack_rows": 8,
			"attack_fps": 18.0,
			"attack_duration": 0.34,
			"combat_script": "res://scripts/combat/hunter_combat.gd",
			"ultimate_cutin_image": "res://assets/players/hunter/portraits/player_hunter_ultimate_character.png",
			"ultimate_cutin_side": "right",
			"ultimate_cutin_width_scale": 0.58,
			"ultimate_cutin_x_offset": 180.0,
			"ultimate_prime_sfx": "res://assets/audio/hunter/hunter_ultimate_prime.mp3",
			"ultimate_impact_sfx": "res://assets/audio/hunter/hunter_ultimate_impact.mp3",
			"ultimate_prime_vfx_sheet": "res://assets/players/hunter/skills/ultimate/hunter_ultimate_blade_ignite_sheet.png",
			"ultimate_prime_vfx_rotate": true,
			"ultimate_prime_vfx_forward_offset": 54.0,
			"ultimate_impact_vfx_sheet": "res://assets/players/hunter/skills/ultimate/hunter_ultimate_activation_impact_sheet.png",
			"select_background_image": "res://assets/ui/character_select/background_hunter_v2.png",
			"select_background_mode": "cover",
			"select_background_focus": Vector2(0.5, 0.5),
			"info_side": "left",
			"info_width": 470.0,
			"detail_image": "res://assets/players/hunter/portraits/hunter_select_reference.png",
			"detail_mode": "contain",
			"detail_focus": Vector2(0.5, 0.5),
			"detail_info_side": "right",
			"detail_overlay_color": Color(0.0, 0.0, 0.0, 0.04),
			"theme_color": Color(1.0, 0.18, 0.18),
			"accent_color": Color(0.98, 0.58, 0.48),
			"skills": [
				{
					"name": "Dash",
					"description": "Same hunter combat kit, using the generated attack animation test sheet.",
					"icon_label": "D",
					"icon_shape": "step",
					"icon_path": "res://assets/ui/hud/hunter_skill_dash_casual_v2.png",
					"color": Color(0.65, 0.08, 0.1),
				},
			],
		},
	]


static func get_slot_count() -> int:
	return maxi(MIN_SLOT_COUNT, get_characters().size())


static func get_character(character_id: String) -> Dictionary:
	for character in get_characters():
		if character["id"] == character_id:
			return character
	return {}


static func find_character_index(character_id: String) -> int:
	var characters := get_characters()
	for index in range(characters.size()):
		if characters[index]["id"] == character_id:
			return index
	return 0
